#!/usr/bin/env bash
VERS="0.4-rc1"
[ -t 1 ] && . colors

echo
echo "${RED}.:Unoffical:. AMD OpenCL Installer v${VERS}${NOCOLOR} by bwminer03"

amdgpuVer=$1
rocmVer=$2

[[ -e /var/run/hive/MINER_RUN ]] && miner_run=1 || miner_run=0

function _check_dist {
    dist=`lsb_release -sr |tr -d "\r\n" |tr -d "."`
    [[ $dist -lt "2004" ]] && echo "${YELLOW}Warning! Version 5.3 and above work only on Ubuntu 20.04 image.${NOCOLOR}"
}

function _uninstall {
	if [[ $miner_run -eq 1 && $(gpu-detect AMD) -gt 0 ]]; then
		echo "${CYAN}> Stopping mining ${NOCOLOR}"
		miner stop > /dev/null 2>&1
	fi
	echo "${CYAN}> Uninstall previous AMDGPU and ROCm OpenCL libs ...${NOCOLOR}"
	apt purge -y hive-opencl-* 1> /dev/null 2> /dev/null
	apt purge -y hive-amdgpu-* hive-rocm-* 1> /dev/null 2> /dev/null
}

function _check {
	[[ -e /opt/amdgpu/VERSION ]]  && cur_amd=`cat /opt/amdgpu/VERSION` || cur_amd="Unknown"
	[[ -e /opt/rocm/VERSION ]]  && cur_rocm=`cat /opt/rocm/VERSION` || cur_rocm="Unknown"
	echo "${CYAN}> Current installed OpenCL libs:  AMDGPU: ${YELLOW}$cur_amd${CYAN}  ROCM: ${YELLOW}$cur_rocm${NOCOLOR}"
#	echo ""
}

function _check_availible {

#Show me the money


echo "${GREEN}Available Releases:${NOCOLOR}"

# Fetch the releases and extract names
releases=$(wget -q -O - https://api.github.com/repos/bwminer03/amd-rocm/releases | \
           grep -oP '"tag_name": "\K(.*?)(?=")')

# Display numbered list of releases
echo "$releases" | nl -w2 -s'. '

# Prompt for release selection
read -p "Please Select a Release: " release_number

# Get the selected release by number
release_name=$(echo "$releases" | sed -n "${release_number}p")

if [ -z "$release_name" ]; then
    echo "${RED}Invalid selection.${NOCOLOR}"
    exit 1
fi

# Fetch assets for the selected release
assets=$(wget -q -O - "https://api.github.com/repos/bwminer03/amd-rocm/releases/tags/$release_name" | \
         grep -oP '"browser_download_url": "\K(.*?)(?=")' | \
         grep "deb")

# Check if any assets were found
if [ -z "$assets" ]; then
    echo "${RED}Sorry, seems to be missing.¯\_(ツ)_/¯ ${NOCOLOR}"
    exit 1
fi

# Select the first asset for download
asset_name=$(echo "$assets" | head -n 1)

# Check if the asset name is valid
if [ -z "$asset_name" ]; then
    echo "${RED}No file for download.¯\_(ツ)_/¯ ${NOCOLOR}"
    exit 1
fi
# Download the asset
echo "${YELLOW}Downloading $asset_name...${NOCOLOR}"
wget -O "${asset_name##*/}" "$asset_name"

if [[ $? -eq 0 ]]; then
    echo "${GREEN}Download completed successfully.【ツ】${NOCOLOR}"
    
    # Install the downloaded .deb package
    echo "${YELLOW}Installing ${asset_name##*/}...${NOCOLOR}"
    sudo dpkg -i "${asset_name##*/}"

    if [[ $? -eq 0 ]]; then
        echo "${GREEN}Installation completed successfully.【ツ】${NOCOLOR}"
        
        # Uninstall previous libs
        echo "${CYAN}> Remove any previously installed OpenCL libs...${NOCOLOR}"
        [[ -e /opt/amdgpu/VERSION ]] && _uninstall

        # Install new (reinstall) libs
        echo "${CYAN}> Install AMDGPU: ${YELLOW}$amdgpuVer${CYAN} and ROCM: ${YELLOW}$rocmVer${CYAN} OpenCL libs...${NOCOLOR}"
        sudo apt install -y hive-amdgpu-$amdgpuVer hive-rocm-$rocmVer

        # Restart mining if applicable
        if [[ $miner_run -eq 1 ]]; then
            echo "${CYAN}> Restart mining ${NOCOLOR}"
            miner start > /dev/null 2>&1
        fi

        # Call hello redetect and _check functions
        hello redetect
        _check
    else
        echo "${RED}Installation failed. Please check the errors above.${NOCOLOR}"
        echo "${YELLOW}Attempting to fix missing dependencies...${NOCOLOR}"
        sudo apt-get install -f
    fi
else
    echo "${RED}Failed to download the asset.${NOCOLOR}"
fi
}

}


if [[ -z $rocmVer ]]; then
	case $amdgpuVer in
		20.40)
			rocmVer="3.5"
			;;
		21.40)
			rocmVer="4.5"
			;;
		21.50)
			rocmVer="5.0"
			;;
		22.10)
			rocmVer="5.1"
			;;
		22.20)
			rocmVer="5.2"
			;;
		5.3)
			rocmVer="5.3"
			;;
		5.4)
			rocmVer="5.4"
			;;
		5.5)
			rocmVer="5.5"
			;;
		5.6)
			rocmVer="5.6"
			;;
		5.7)
			rocmVer="5.7"
			;;
		5.8)
			rocmVer="5.8"
			;;
		5.9)
			rocmVer="5.9"
			;;
		6.0)
			rocmVer="6.0"
			;;
		6.1)
			rocmVer="6.1"
			;;
		6.2)
			rocmVer="6.2"
			;;

		*)
			_check_availible
			_check_dist
			exit 1
			;;
	esac
	echo "${CYAN}> Not specified ROCM version, use ${YELLOW}$rocmVer${CYAN} for this version of amdgpu by default${NOCOLOR}"
fi

# Uninstall previous libs
echo "${CYAN}> Remove any previously installed OpenCL libs...${NOCOLOR}"
[[ -e /opt/amdgpu/VERSION ]] && _uninstall
# Install new (reinstall) libs
echo "${CYAN}> Install AMDGPU: ${YELLOW}$amdgpuVer${CYAN} and ROCM: ${YELLOW}$rocmVer${CYAN} OpenCL libs...${NOCOLOR}"
apt install -y hive-amdgpu-$amdgpuVer hive-rocm-$rocmVer
# Restart mining && show installed libs
[[ $miner_run -eq 1 ]] && echo "${CYAN}> Restart mining ${NOCOLOR}" && miner start > /dev/null 2>&1
hello redetect
 _check
